### ISSUE TITLE
append 0 to single digit numbers

### ISSUE THREAD

**Issue by terygasmen** [terygasmen/panpan-pomodoro-timer-notes-and-session-tracker-package#1]

**Comment by ionutrogojan** [comment]
I tried to fix your problem [here](https://github.com/terygasmen/panpan-pomodoro-timer-notes-and-session-tracker-package/pull/5#issue-1173337368).
Hope it helps.

**Comment by terygasmen** [comment]
thank you so much for your contribution! it helps so much!

**Comment by ionutrogojan** [comment]
No problem, good luck with your project ^_^
